DEFAULT_TOPICS = [
    'corn',
    'apple butter',
    'red velvet',
    'block island',
    'charges',
    'ukulele',
    'moss',
    'fedora',
    'go away',
    'so fabulous',
    'curtain rod',
    'lawn care',
    'volunteer',
    'monarch',
    'the washington post',
    'stubbed my toe',
    'violet',
    'concerto',
    'yellow',
    'nails',
    'honeycrisp'
    'rain',
    'laugh',
    'Calgary',
    'Park Hill',
    'golfcart races',
    'Reston',
    'deluge',
    'ginger syrup',
    'tormented',
    'pee',
    'pillow',
    'climbing',
    'walk the line',
    'throw',
    'a rolling stone gathers no moss',
    'spun around',
    'brown eyes',
    'drew merrily',
    'forgot quickly',
    'died slowly',
    'capris',
    'fridge magnet',
    'curly hair',
    'sleep',
    'work',
    'play',
    'run',
    'swim',
    'dance',
    'eat',
    'hide',
    'run away',
    'cook',
    'reward',
    'regret ',
    'reply',
    'replay',
    'refine',
    'redistribute',
    'renegotiate',
    'mother',
    'father ',
    'baby',
    'sister',
    'brother',
    'uncle'
]
